name: Selenium Java Tests
on:
  workflow_dispatch: # Permet à n8n de déclencher le test via API

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests with Maven
        run: mvn test  # <--- C'EST CETTE LIGNE QUI DOIT TOURNER

      - name: Send Report to n8n
        if: always()
        run: |
            curl -X POST "https://hela.app.n8n.cloud/webhook-test/resultselenium" \
              -F "status=${{ job.status }}" \
              -F "report=@target/cucumber-reports.html"
          
          
          //Actuellement, ton rapport (class testRunner) est généré dans le dossier target/ 
          de la machine virtuelle GitHub, mais il est détruit dès que le job se termine. 
          Il faut l' "uploader" pour qu'il soit accessible via une URL ou envoyé vers n8n.

      - name: Upload Cucumber Report
        if: always() # On veut le rapport même si le test échoue !
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports.html
